[package]
name = "erlang_llama_cpp_nif"
version = "0.0.1"
authors = []
edition = "2021"

[lib]
name = "erlang_llama_cpp_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
llama_cpp = {version = "0.3.1"}
